### ISSUE TITLE
Create logo with Adobe Illustrator

### ISSUE THREAD

**Issue by daridjcm** [Michael-Liendo/linx#12]
Logotype: ![Logotype - Linx](https://github.com/user-attachments/assets/2010de6b-bb70-438a-9aae-d637fdc87c37)
HEX color code: ![Palette Color - Linx](https://github.com/user-attachments/assets/6bba905c-3223-485e-bdf7-4008ded63b7f)
Isotype: 
![Isotype - Linx](https://github.com/user-attachments/assets/4a05e7d8-7ad1-41df-b093-b7b251be1866)

**Comment by Michael-Liendo** [comment]
Yeah! you can contribute with a logo in this issue

**Comment by Michael-Liendo** [comment]
Thanks you! @Daridjcm you can send the logo without the text, like a isotype logo
